name: Build and Publish to PyPI

on:
  push:
    tags:
      - "*.*.*"  # Trigger workflow on versioned tags, e.g., 0.5.0

jobs:
  build:
    name: Build and Publish Package
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install build tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # 4. Build the package
      - name: Build package
        run: python -m build

      # 5. Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
